all:
  children:
    network:
      children:
        switches:
          hosts:
            AristaSwitch:
              ansible_host: 192.168.5.111
              ansible_network_os: arista.eos.eos
              ansible_connection: ansible.netcommon.network_cli
              ansible_become: true
              ansible_become_method: enable
            ciscoswitch:
              ansible_host: 192.168.4.204
    gitlab:
      hosts:
        linux02:
          ansible_host: 192.168.4.82
          ansible_user: adminuser
          ansible_become: true
          ansible_connection: ssh
          ansible_ssh_pass: adminpassword
          ansible_become_method: sudo
          ansible_become_pass: adminpassword
