---
- name: Setup Gitlab onto Linux Server
  hosts: linux02
  gather_facts: false
  remote_user: "adminuser"
  connection: ssh
  become: true

  tasks:
    - name: Remove Gitlab Container on Docker
      ansible.builtin.include_role:
        name: setup_gitlab
      vars:
        setup_gitlab_state: stopped
