---
- name: Setup Kafka onto Linux Server
  hosts: linux02
  gather_facts: false
  remote_user: "adminuser"
  connection: ssh
  become: true

  tasks:
    - name: Setup Docker Container Engine on Server
      ansible.builtin.include_role:
        name: setup_docker

    - name: Setup Kafka on Docker
      ansible.builtin.include_role:
        name: setup_kafka
      vars:
        setup_kafka_state: present
