---
- name: Setup Gitlab onto Linux Server
  hosts: linux02
  gather_facts: false
  remote_user: "adminuser"
  connection: ssh
  become: true

  tasks:
    - name: Remove Kafka on Docker
      ansible.builtin.include_role:
        name: setup_kafka
      vars:
        setup_kafka_state: stopped
